### ISSUE TITLE
Question about preamble

### ISSUE THREAD

**Issue by Kludex** [defnull/multipart#65]
Hi @defnull

I'm trying to understand when should we error on some situations.

The situation I have in hands now is this one:

```py
from multipart import PushMultipartParser

parser = PushMultipartParser(b"boundary123")

for r in parser.parse(b"--boundary123\r"):
    ...

for r in parser.parse(b"\n"):
    ...

print(parser._state)
```
What is the expected state?

I would expect the whole `--boundary123\r` to be buffered, and then `\n` to be included on the buffer, and have the state becoming `HEADER`, but that's not what happens. The buffer is partially consumed - the offset becomes `-3` after the first chunk, and `23\r` remain on the buffer. Then `\n` is added.

What do you think? Is this behavior correct?

**Comment by defnull** [comment]
That sounds like a bug I already found and fixed in #64. It's unlikely to trigger because the first chunk is usually bigger than the boundary, but a new test case that feeds single bytes into the parser found it.

**Comment by defnull** [comment]
The PR is now ready and has 100% coverage again. Would you like to give it a try?

**Comment by Kludex** [comment]
I've tested. It does move to `HEADER` now. Thanks.

I'm interested in creating a test suite language agnostic for multipart. My idea is to have something like:
```toml
[[tests]]
name = "preamble_cr_after_delimiter"
data_files = ["preamble_cr_after_delimiter_1.http", "preamble_cr_after_delimiter_2.http]

[tests.expected]
error = false
incomplete = true
# headers = ?
# data = ?
```

The `preamble_cr_after_delimiter_1.http`:
```
--boundary\r
```
The `preamble_cr_after_delimiter_2.http`:
```
--boundary\r\n
```

What do you think?
